#!/bin/bash

working_dir="/usr/local/go/src/github.com/cghsystems/godata"

docker run -v "${PWD}":"${working_dir}" -w ${working_dir} cghsystems/golang \
    /bin/bash -c \
    "godep restore ; \
     redis-server ./assets/redis/redis.conf; \
    ginkgo -r"


