jobs:
  - name: godata-unit
    plan:
      - get: godata
        trigger: true
      - task: unit
        file: godata/ci/unit.yml

resources:
  - name: godata
    type: git
    source:
      uri: https://github.com/cghsystems/godata.git
      branch: master
